// <auto-generated />
using System;
using APIHotProducts.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIHotProducts.Migrations
{
    [DbContext(typeof(APIHotProductsContext))]
    [Migration("20220620202916_DeleteStatus")]
    partial class DeleteStatus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("APIHotProducts.Models.Target", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("BCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BLotNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C1Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("C1Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("C1LotNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C1Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C2Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("C2Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("C2LotNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C2Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CLotNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WLotNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Target");
                });
#pragma warning restore 612, 618
        }
    }
}
